debug: true

spring:
  application:
    name: demo
    version: 1.0
    environment: DEV
    
app:
  service-principal: HTTP/localhost
  user-principal: client/localhost
  keytab-location: @project.basedir@\\krb-test-workdir\\example.keytab
  access-url: http://localhost:8080/
  
